requisitos_entregaveis:
- nome: Nome claro e específico
  obrigatorio: true
- descricao: Descrição detalhada
  obrigatorio: true
- dependencias: Lista de dependências necessárias
  obrigatorio: true
- exemplo_uso: Exemplo prático de uso
  obrigatorio: true
- criterios_aceitacao: Critérios mensuráveis
  obrigatorio: true
- obrigatorio: true
  resolucao_problemas: Problemas e soluções
- obrigatorio: true
  passos_implementacao: Passos detalhados
