name: Validar Arquivos YAML

on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint

      - name: Rodar yamllint
        run: yamllint . --format colored