name: Verificar Markdown

on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Rodar markdownlint
        run: markdownlint "**/*.md" --ignore node_modules