name: Lint Python Code

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Rodar flake8
        run: |
          flake8 agents/ scripts/ evaluators/ --max-line-length=120 --exclude=__init__.py