name: Atualizar índice da documentação

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/pr/**'
      - 'scripts/generate_docs_index.py'

jobs:
  update-docs-index:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar Python e dependências
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Executar script para gerar índice
        run: python scripts/generate_docs_index.py

      - name: Commit e push de atualização
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/README.md
          git commit -m "Atualiza índice automático de documentação após alteração em docs/pr" || echo "Nenhuma alteração"
          git push