name: Atualizar estrutura do projeto (TREE.md)

on:
  push:
    branches:
      - main

jobs:
  generate-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar UV
        run: |
          curl -Ls https://astral.sh/uv/install.sh | sh

      - name: Executar script Python para gerar TREE.md
        run: |
          uv pip install rich
          uv venv
          uv pip install rich
          uv python scripts/generate_tree.py

      - name: Commit e push do arquivo TREE.md
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add TREE.md
          git commit -m "Atualiza TREE.md automaticamente após push"
          git push
